import{S as v,i as P,a as M}from"./assets/vendor-CNqCr-V-.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const h=document.querySelector(".gallery"),y=document.querySelector(".loader"),f=document.querySelector(".showLoad"),$=()=>h.innerHTML="",m=()=>y.classList.add("show"),p=()=>y.classList.remove("show"),g=()=>f.classList.add("show"),u=()=>f.classList.remove("show");function L(r){const t=r.map(({webformatURL:i,largeImageURL:e,tags:o,likes:l,views:b,comments:S,downloads:q})=>`<li class ="gallery-item">
                    <a class = "gallery-link" href="${e}">
                    <img
                        class = "gallery-image"    
                        src = "${i}"
                        alt ="${o}"
                        />
                    </a>
                     <ul class="info">
            <li>Likes<p>${l}</p></li>
            <li>Views<p>${b}</p></li>
            <li>Comments<p>${S}</p></li>
            <li>Downloads<p>${q}</p></li>
            </ul>
                    </li>`).join("");h.insertAdjacentHTML("beforeend",t),new v(".gallery-link",{captionDelay:250,showCounter:!1,captionsData:"alt"}).refresh()}const a=(r,t)=>{P[r]({title:r.charAt(0).toUpperCase()+r.slice(1),message:t,position:"topRight"})};let d=15;const x="https://pixabay.com/api/",B="53507836-a90b7328b368e53f321449aea",w=async(r,t)=>{try{return(await M.get(x,{params:{key:B,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:d,page:t}})).data}catch{a("error","Problems")}},O=document.querySelector(".form"),A=document.querySelector('[name="search-text"]'),E=document.querySelector(".showLoad");let c="",n=1;O.addEventListener("submit",async r=>{if(r.preventDefault(),c=A.value.trim(),u(),c===""){a("error","Невалидный ввод");return}$(),n=1,m();try{const t=await w(c,n);if(t.hits.length===0)a("error","Sorry, there are no images matching your search query. Please try again!");else{const s=Math.ceil(t.totalHits/d);n>s?a("info","We're sorry, but you've reached the end of search results."):(L(t.hits),g())}}catch{a("error","Sorry, there are no images matching your search query. Please try again!")}finally{p()}});E.addEventListener("click",async()=>{n+=1,u(),m();try{const r=await w(c,n),t=Math.ceil(r.totalHits/d);if(n>t)u(),a("info","We're sorry, but you've reached the end of search results.");else{L(r.hits);const s=document.querySelector(".gallery-item");if(s){const i=s.getBoundingClientRect();window.scrollBy({top:i.height*2,behavior:"smooth"})}g()}}catch{a("error","We're sorry, щось трапилося")}finally{p()}});
//# sourceMappingURL=index.js.map
