import{a as q,S as v,i as M}from"./assets/vendor-CNqCr-V-.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();let d=15;const $="https://pixabay.com/api/",x="53507836-a90b7328b368e53f321449aea",h=async(r,t)=>{try{return(await q.get($,{params:{key:x,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:d,page:t}})).data}catch{a("error","Problems")}},y=document.querySelector(".gallery"),m=document.querySelector(".loader"),p=document.querySelector(".showLoad"),B=()=>y.innerHTML="",f=()=>m.classList.add("show"),g=()=>m.classList.remove("show"),L=()=>p.classList.add("show"),u=()=>p.classList.remove("show");function w(r){const t=r.map(({webformatURL:i,largeImageURL:e,tags:o,likes:l,views:b,comments:S,downloads:P})=>`<li class ="gallery-item">
                    <a class = "gallery-link" href="${e}">
                    <img
                        class = "gallery-image"    
                        src = "${i}"
                        alt ="${o}"
                        />
                    </a>
                     <ul class="info">
            <li>Likes<p>${l}</p></li>
            <li>Views<p>${b}</p></li>
            <li>Comments<p>${S}</p></li>
            <li>Downloads<p>${P}</p></li>
            </ul>
                    </li>`).join("");y.insertAdjacentHTML("beforeend",t),new v(".gallery-link",{captionDelay:250,showCounter:!1,captionsData:"alt"}).refresh()}const O=document.querySelector(".form"),A=document.querySelector('[name="search-text"]'),E=document.querySelector(".showLoad"),a=(r,t)=>{M[r]({title:r.charAt(0).toUpperCase()+r.slice(1),message:t,position:"topRight"})};let c="",n=1;O.addEventListener("submit",async r=>{if(r.preventDefault(),c=A.value.trim(),B(),u(),c===""){a("error","Невалидный ввод");return}n=1,f();try{const t=await h(c,n);if(t.hits.length===0)a("error","Sorry, there are no images matching your search query. Please try again!");else{const s=Math.ceil(t.totalHits/d);n>s?(a("info","We're sorry, but you've reached the end of search results."),u()):(w(t.hits),L())}}catch{a("error","Sorry, there are no images matching your search query. Please try again!")}finally{g()}});E.addEventListener("click",async()=>{n+=1,u(),f();try{const r=await h(c,n);if(Math.ceil(r.totalHits/d)<n)u(),a("error","We're sorry, but you've reached the end of search results.");else{w(r.hits);const i=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:i.height*2,behavior:"smooth"}),L()}}catch{a("error","We're sorry, щось трапилося")}finally{g()}});
//# sourceMappingURL=index.js.map
